### PR TITLE
stedi updates to readme

### PR DESCRIPTION
**Pull request by dkanter14**
- Changed EDI Core to EDI Translate
- Added section on guide builders, add stedi guides as item
- Changed github repo to write-edi-demo

### CODE REVIEW

**Comment by dkanter14** [comment]
Hi @michaelachrisco! I added a few new resources to this repo, and removed some older items as well, hoping you can take a look!

**Review by michaelachrisco — CHANGES_REQUESTED** [review]
Awesome, thanks for contributing @dkanter14! 

There are two small corrections that I think would be necessary for merging. I think that we should not have PRs be links as there may be changes that occur later that do not get included within the link. I also believe the markdown is incorrect on one of the links. If you can fix those issues, I think this should be good to go for merging.

**Comment by dkanter14** [comment]
Hi @michaelachrisco - thanks for the catches. The Markdown was indeed broken, and I miscopied a link. I updated both. Let me know if you have any more issues before emerging!

**Review by michaelachrisco — APPROVED** [review]
LGMT! Thanks for making the changes.

**Pull request merged**
