### PR TITLE
Syntax Highlighters: +1

### PR DESCRIPTION
**Pull request by shaedrich**

### CODE REVIEW

**Review by michaelachrisco — CHANGES_REQUESTED** [review]
Thanks for the contribution, @shaedrich ! This looks like a really cool, I use VSCode too. 

Dont worry about the CI at this time, looks like a site is down ATM. I may have to make another PR to address. 

Can you please change the prefix on your resource? Let me know if you have any questions.

**Comment by shaedrich** [comment]
You're welcome, @michaelachrisco. Sure thing, I changed it. I found this extension when I was looking for something that was a little more than just formatting from one line to multiple and back.

**Review by michaelachrisco — APPROVED** [review]
Awesome thanks!!

**Comment by shaedrich** [comment]
You're welcome!!

**Pull request merged**
